# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

target 'SharpnezCore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SharpnezCore

  target 'SharpnezCoreTests' do
    pod 'SnapshotTesting', '~> 1.9'
  end

end
