# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.6.0'

end

target 'SharpnezCore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SharpnezCore

  target 'SharpnezCoreTests' do
    # Pods for testing
  end

end